baseURL = https://opensource-demo.orangehrmlive.com/
baseURL1 = https://automationexercise.com/

username6 =maaco0216@gmail.com
password6 =hjgjyt2


browser = chrome
AIFilePath =C:\\CDAutomation\\ClaimDriver\\TestData\\AIIncomingDataFile.xlsx

chromepath=./Drivers\\chromedriver.exe
iepath=./Drivers\\IEDriverServer.exe
firefoxpath=./Drivers\\geckodriver.exe